Issue #21497: faulthandler functions now raise a better error if sys.stderr is None: RuntimeError("sys.stderr is None") instead of AttributeError("'NoneType' object has no attribute 'fileno'").
--HG--
branch : 3.4